docs: expand the section on commit messages
osbuild/osbuild.github.io pull request #116
Opened 2024-09-10 09:16 UTC by mvo5

This comit expand on the commit messages section and makes it more clear why they are important and what should be part of them.

There are many good guides on this so it's fine to keep this brief but I think it was a little bit to concise :)

It also links to a good commit message example, I am open for suggestions here though, while this is good (as pretty much any from Christian) I'm sure there are even better ones.

2024-09-10 09:53 UTC, ondrejbudai submitted a review, later dismissed
:heart_eyes: Thanks!

2024-09-25 12:28 UTC, croissanne submitted a review, later dismissed

2024-09-25 14:28 UTC, schuellerf requested changes
I like it, thanks!
…just a minor typo

2024-09-25 14:28 UTC, schuellerf commented on docs/developer-guide/01-general/workflow.md
> +commit was writen so that a `git show <commit>` provides a concise
```suggestion
commit was written so that a `git show <commit>` provides a concise
```

2024-10-07 07:28 UTC, mvo5 commented on docs/developer-guide/01-general/workflow.md
> +commit was writen so that a `git show <commit>` provides a concise
Thanks! Pushed an update

2024-10-07 09:01 UTC, schuellerf approved these changes, later dismissed
lgtm, thanks!

2024-10-08 08:39 UTC, achilleas-k reviewed
Some suggestions for potential improvements, if you agree.

2024-10-08 08:39 UTC, achilleas-k commented on docs/developer-guide/01-general/workflow.md
> +A good commit message will help our future selfs to get back into the
```suggestion
A good commit message will help our future selves to get back into the
```

2024-10-08 08:39 UTC, achilleas-k commented on docs/developer-guide/01-general/workflow.md
> +decisions/considerations/background that were important when the
```suggestion
decisions, considerations, and background information that were important when the
```

2024-10-08 08:39 UTC, achilleas-k commented on docs/developer-guide/01-general/workflow.md
> +way to (re)acquire this context. See [this](https://github.com/osbuild/osbuild/commit/a2e212bb2641cf28e5701ad4a2202261c2c5ee5c) as an example.
```suggestion
way to (re)acquire this context. See [this commit message](https://github.com/osbuild/osbuild/commit/a2e212bb2641cf28e5701ad4a2202261c2c5ee5c) as an example.
```

2024-10-08 08:41 UTC, achilleas-k commented on docs/developer-guide/01-general/workflow.md
> +way to (re)acquire this context. See [this](https://github.com/osbuild/osbuild/commit/a2e212bb2641cf28e5701ad4a2202261c2c5ee5c) as an example.
Or
```suggestion
way to (re)acquire this context. See [this commit](https://github.com/osbuild/osbuild/commit/a2e212bb2641cf28e5701ad4a2202261c2c5ee5c) as an example.
```

2024-10-08 11:13 UTC, ochosi approved these changes, later dismissed
@achilleas-k Already left some nice wording suggestions - I'm all good with the content!

2024-10-10 16:04 UTC, achilleas-k approved these changes
Wonderful!!

2024-10-10 16:06 UTC, merged