user-guide: new chapter about firstboot
osbuild/osbuild.github.io pull request #120
Opened 2024-09-17 14:13 UTC by lzap

SSIA

2024-09-17 20:58 UTC, ochosi reviewed
Is this a typo? If so it's there thrice

2024-09-17 20:58 UTC, ochosi commented on docs/user-guide/08-firstboot.md
> +[[customizations.files]
```suggestion
[[customizations.files]]
```

2024-09-17 20:58 UTC, ochosi commented on docs/user-guide/08-firstboot.md
> +[[customizations.files]
This looks like a typo

2024-09-18 14:10 UTC, ochosi requested changes
I think there are some errors in the markdown (which is why the test-build fails).

2024-09-20 12:02 UTC, lzap commented
Fixed.

2024-09-25 13:00 UTC, lzap commented
Rebased @ochosi

2024-09-26 14:23 UTC, ochosi approved these changes
LGTM! Thank you <3

2024-09-26 14:23 UTC, merged

2024-09-26 15:07 UTC, lzap commented
I am surprised it rendered fine, I was pretty sure I messed up, I mean, I would have to do `npm install` which I wanted to avoid... :-)

https://osbuild.org/docs/user-guide/firstboot