OpenSCAP json tailoring (HMS-4462)
osbuild/osbuild.github.io pull request #97
Opened 2024-07-23 17:06 UTC by kingsleyzissou

This depends on https://github.com/osbuild/osbuild-composer/pull/4272

2024-08-13 14:01 UTC, schuellerf requested changes

2024-08-13 14:01 UTC, schuellerf commented on docs/user-guide/01-blueprint-reference.md
> +A basic example can be found [here](https://github.com/ComplianceAsCode/schemas/blob/b91c8e196a8cc515e0cc7f10b2c5a02b4179c0e5/tailoring/example-basic.json_tailoring).
link is dead :-/
the `_tailoring` seems to be too much
```suggestion
A basic example can be found [here](https://github.com/ComplianceAsCode/schemas/blob/b91c8e196a8cc515e0cc7f10b2c5a02b4179c0e5/tailoring/example-basic.json).
```

2024-08-13 14:01 UTC, schuellerf commented on docs/user-guide/01-blueprint-reference.md
> +Note: users will need to use [custom files](#Files) to save the json tailoring file to the image. The generated xml tailoring file is saved to
I think this has to be written in small letters to work always
```suggestion
Note: users will need to use [custom files](#files) to save the json tailoring file to the image. The generated xml tailoring file is saved to
```

2024-08-13 15:37 UTC, schuellerf commented
sorry - did a rebase - I hope that was ok :-|

2024-08-13 18:06 UTC, kingsleyzissou commented on docs/user-guide/01-blueprint-reference.md
> +A basic example can be found [here](https://github.com/ComplianceAsCode/schemas/blob/b91c8e196a8cc515e0cc7f10b2c5a02b4179c0e5/tailoring/example-basic.json_tailoring).
This was a silly typing mistake. Thanks for finding

2024-08-13 18:07 UTC, kingsleyzissou commented
> sorry - did a rebase - I hope that was ok :-|

No worries, I've just fixed and rebased again

2024-08-14 08:37 UTC, schuellerf requested changes

2024-08-14 08:37 UTC, schuellerf commented on docs/user-guide/01-blueprint-reference.md
> +### OpenSCAP JSON Tailoring
please add this bullet for the overview (and then also the manual anchor is needed)
```suggestion
### OpenSCAP JSON Tailoring 🔵 {#openscap-json-tailoring}
```

2024-08-14 08:37 UTC, schuellerf commented on docs/user-guide/01-blueprint-reference.md
> +Note: users will need to use [custom files](#files) to save the json tailoring file to the image. The generated xml tailoring file is saved to
nit-pick
```suggestion
Note: users will need to use [custom files](#files) to save the json tailoring file to the image. The generated XML tailoring file is saved to
```

2024-08-14 10:22 UTC, ochosi approved these changes
LGTM!

2024-08-14 18:20 UTC, schuellerf approved these changes

2024-08-15 08:59 UTC, merged